<script>
import { defineComponent } from "vue";

export default defineComponent({
  props: { loading: { type: Boolean, default: false } },
});
</script>

<template>
  <div v-if="loading" class="d-flex align-items-center justify-content-center">
    <div class="loadingio-spinner-dual-ring-6r8yc8cc4wk">
      <div class="ldio-rtxs6qh92u">
        <div></div>
        <div><div></div></div>
      </div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-rtxs6qh92u {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-rtxs6qh92u div {
  box-sizing: border-box !important;
}
.ldio-rtxs6qh92u > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #e23744 transparent #e23744 transparent;
  animation: ldio-rtxs6qh92u 1s linear infinite;
}
.ldio-rtxs6qh92u > div:nth-child(2) {
  border-color: transparent;
}
.ldio-rtxs6qh92u > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-rtxs6qh92u > div:nth-child(2) div:before,
.ldio-rtxs6qh92u > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #e23744;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #e23744;
}
.ldio-rtxs6qh92u > div:nth-child(2) div:after {
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #e23744;
}
.loadingio-spinner-dual-ring-6r8yc8cc4wk {
  width: 40px;
  height: 40px;
  display: inline-block;
  overflow: hidden;
}
.ldio-rtxs6qh92u {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.4);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-rtxs6qh92u div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
